import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Upload, Camera, Download } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useToast } from "@/hooks/use-toast";
import MedicalLoader from "@/components/MedicalLoader";

interface MedicalReport {
  name: string;
  age: number;
  gender: string;
  dateOfTest: string;
  bloodType: string;
  hemoglobin: string;
  wbc: string;
  platelets: string;
  glucose: string;
  cholesterol: string;
  diagnosis: string;
  recommendations: string;
}

const Dashboard = () => {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<MedicalReport | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const cameraInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setSelectedImage(reader.result as string);
        processImage();
      };
      reader.readAsDataURL(file);
    }
  };

  const processImage = async () => {
    setIsLoading(true);
    
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    // Mock report data
    const mockReport: MedicalReport = {
      name: "John Doe",
      age: 35,
      gender: "Male",
      dateOfTest: new Date().toLocaleDateString(),
      bloodType: "O+",
      hemoglobin: "14.5 g/dL",
      wbc: "7,500 cells/μL",
      platelets: "250,000/μL",
      glucose: "95 mg/dL",
      cholesterol: "180 mg/dL",
      diagnosis: "All parameters are within normal range. Patient shows good overall health indicators.",
      recommendations: "Continue maintaining a healthy lifestyle. Regular exercise and balanced diet recommended. Follow-up check-up in 6 months."
    };
    
    setReport(mockReport);
    setIsLoading(false);
    toast({
      title: "Report Generated",
      description: "Your medical report has been successfully generated.",
    });
  };

  const handleDownloadReport = () => {
    if (!report) return;
    
    const reportText = `
MEDICAL REPORT
=============

Patient Information:
Name: ${report.name}
Age: ${report.age}
Gender: ${report.gender}
Date of Test: ${report.dateOfTest}

Test Results:
Blood Type: ${report.bloodType}
Hemoglobin: ${report.hemoglobin}
WBC Count: ${report.wbc}
Platelet Count: ${report.platelets}
Blood Glucose: ${report.glucose}
Cholesterol: ${report.cholesterol}

Diagnosis:
${report.diagnosis}

Recommendations:
${report.recommendations}

Generated by Medhyamed - Where Reports Speak Clearly
    `;
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medical-report-${report.name.replace(/\s+/g, '-')}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    toast({
      title: "Report Downloaded",
      description: "Your medical report has been downloaded successfully.",
    });
  };

  const resetUpload = () => {
    setSelectedImage(null);
    setReport(null);
    setIsLoading(false);
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-1 py-12 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-background to-accent">
        <div className="container mx-auto max-w-6xl">
          {!report && !isLoading && (
            <div className="text-center space-y-8">
              <div className="space-y-4 animate-fade-in">
                <h1 className="text-4xl md:text-5xl font-bold text-foreground">
                  Upload Medical Report
                </h1>
                <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                  Upload an image of your medical report to generate a detailed analysis
                </p>
              </div>

              <Card className="max-w-2xl mx-auto p-8 animate-scale-in hover-scale transition-all">
                <CardContent className="space-y-6">
                  {!selectedImage ? (
                    <>
                      <div className="flex flex-col items-center justify-center space-y-4 py-12">
                        <Upload className="h-24 w-24 text-primary animate-pulse" />
                        <p className="text-lg text-muted-foreground">
                          Choose how to upload your report
                        </p>
                      </div>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Button
                          size="lg"
                          className="h-20 text-lg"
                          onClick={() => fileInputRef.current?.click()}
                        >
                          <Upload className="mr-2 h-6 w-6" />
                          Browse Files
                        </Button>
                        
                        <Button
                          size="lg"
                          variant="outline"
                          className="h-20 text-lg"
                          onClick={() => cameraInputRef.current?.click()}
                        >
                          <Camera className="mr-2 h-6 w-6" />
                          Take Photo
                        </Button>
                      </div>

                      <input
                        ref={fileInputRef}
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={handleFileSelect}
                      />
                      
                      <input
                        ref={cameraInputRef}
                        type="file"
                        accept="image/*"
                        capture="environment"
                        className="hidden"
                        onChange={handleFileSelect}
                      />
                    </>
                  ) : (
                    <div className="space-y-4">
                      <img
                        src={selectedImage}
                        alt="Uploaded report"
                        className="w-full max-h-96 object-contain rounded-lg"
                      />
                      <Button onClick={resetUpload} variant="outline" className="w-full">
                        Upload Different Image
                      </Button>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          )}

          {isLoading && (
            <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-8">
              <MedicalLoader />
              <div className="text-center space-y-2">
                <h2 className="text-2xl font-bold text-foreground">Analyzing Your Report</h2>
                <p className="text-muted-foreground">Please wait while we process your medical data...</p>
              </div>
            </div>
          )}

          {report && !isLoading && (
            <div className="space-y-6 animate-fade-in">
              <div className="flex justify-between items-center">
                <h2 className="text-3xl font-bold text-foreground">Medical Report</h2>
                <div className="flex gap-2">
                  <Button onClick={handleDownloadReport} className="gap-2">
                    <Download className="h-4 w-4" />
                    Download Report
                  </Button>
                  <Button onClick={resetUpload} variant="outline">
                    New Report
                  </Button>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <Card className="hover-scale transition-all">
                  <CardContent className="p-6 space-y-4">
                    <h3 className="text-xl font-semibold text-primary border-b pb-2">
                      Patient Information
                    </h3>
                    <div className="space-y-2">
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Name:</span>
                        <span className="font-medium">{report.name}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Age:</span>
                        <span className="font-medium">{report.age} years</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Gender:</span>
                        <span className="font-medium">{report.gender}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Date of Test:</span>
                        <span className="font-medium">{report.dateOfTest}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Blood Type:</span>
                        <span className="font-medium">{report.bloodType}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="hover-scale transition-all">
                  <CardContent className="p-6 space-y-4">
                    <h3 className="text-xl font-semibold text-primary border-b pb-2">
                      Test Results
                    </h3>
                    <div className="space-y-2">
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Hemoglobin:</span>
                        <span className="font-medium">{report.hemoglobin}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">WBC Count:</span>
                        <span className="font-medium">{report.wbc}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Platelet Count:</span>
                        <span className="font-medium">{report.platelets}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Blood Glucose:</span>
                        <span className="font-medium">{report.glucose}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Cholesterol:</span>
                        <span className="font-medium">{report.cholesterol}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="lg:col-span-2 hover-scale transition-all">
                  <CardContent className="p-6 space-y-4">
                    <h3 className="text-xl font-semibold text-primary border-b pb-2">
                      Diagnosis
                    </h3>
                    <p className="text-foreground leading-relaxed">{report.diagnosis}</p>
                  </CardContent>
                </Card>

                <Card className="lg:col-span-2 hover-scale transition-all">
                  <CardContent className="p-6 space-y-4">
                    <h3 className="text-xl font-semibold text-secondary border-b pb-2">
                      Recommendations
                    </h3>
                    <p className="text-foreground leading-relaxed">{report.recommendations}</p>
                  </CardContent>
                </Card>
              </div>
            </div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Dashboard;
